import fs from 'node:fs';
import path from 'node:path';
import { fingerprint } from './fingerprint.js';

/** The `generated` map recorded in a project's ai-project.config.json. */
export type Fingerprints = Record<string, string>;

/**
 * Works out which generated files the user has edited since they were written.
 *
 * A file counts as edited when its current contents differ from the fingerprint
 * recorded at generation. Those are the files a regeneration must not touch —
 * overwriting them is silent data loss, and `--force` makes it easy to do by
 * accident.
 *
 * Files absent from `recorded` were never generated by us, or come from a newer
 * version of the generator; either way they are written normally.
 */
export function preservedPaths(
  targetDir: string,
  candidates: readonly string[],
  recorded: Fingerprints | undefined,
): string[] {
  if (!recorded || Object.keys(recorded).length === 0) return [];

  const preserved: string[] = [];

  for (const relative of candidates) {
    const previous = recorded[relative];
    if (previous === undefined) continue;

    const full = path.join(targetDir, ...relative.split('/'));
    if (!fs.existsSync(full)) continue;

    let current: string;
    try {
      current = fs.readFileSync(full, 'utf8');
    } catch {
      continue; // unreadable or binary — leave it to the normal write path
    }

    if (fingerprint(current) !== previous) preserved.push(relative);
  }

  return preserved.sort();
}

/** Reads the `generated` fingerprints from a project's config, if present. */
export function readFingerprints(configFile: string): Fingerprints | undefined {
  if (!fs.existsSync(configFile)) return undefined;

  try {
    const parsed = JSON.parse(fs.readFileSync(configFile, 'utf8')) as {
      generated?: Fingerprints;
    };
    return parsed.generated;
  } catch {
    return undefined;
  }
}
